#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT=$SCRIPT_DIR

cd "$TABTREE_LIB"

TARGET="$ROOT/target"

case $1 in

"translate" )

  TARGET_DOT_TTL="$TARGET/dot.ttl"
  echo "Not implemented yet"

;;

"ontologies" )

  echo ""
  echo "* Make Semantic BPM ontology"
  clj -M:compile-ttl --source "$ROOT/source/sem_bpm_ontology/sem_bpm_ontology.tree" --target "$TARGET/sem_bpm.ttl"

  echo ""
  echo "* Validate Semantic BPM ontology"
  ttl "$TARGET/sem_bpm.ttl"

;;

"chart" )

  CHART="$ROOT/source/charts/$2.tree"
  ONTOLOGY_TABTREE="$ROOT/source/sem_bpm_ontology/sem_bpm_ontology.tree"

  echo ""
  echo "* Check undeclared objects and predicates"
  clj -M:all-undeclared --tabtree $CHART --ignore-keys "" --external-ontology $ONTOLOGY_TABTREE

  echo ""
  echo "* Make chart RDF"
  clj -M:compile-ttl --source $CHART --target "$TARGET/$2.ttl" --ref-tabtree $ONTOLOGY_TABTREE

  echo ""
  echo "* Validate chart RDF"
  ttl "$TARGET/$2.ttl"

  echo ""
  echo "* Incoming and outcoming documents of the workflow:"
  arq --data "$TARGET/$2.ttl" --query $ROOT/sparql/ins_and_outs.rq

;;

esac

cd - 1>/dev/null
